# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Pull-Request-Action

on: [pull_request,push]
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install matplotlib
        pip install coverage
        pip install wemake-python-styleguide
        pip install flake8-isort==3.0.1
    - name: Run Tests
      run: |
        python -m unittest discover
    - name: getCoverage
      run: |
        coverage run -m --source=src unittest discover
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        token: "6aa7d993-de01-42c7-a2aa-4cea9083185b"
    - name: Wemake Python Stylguide
      uses: wemake-services/wemake-python-styleguide@0.13.4
      continue-on-error: true
      with:
          reporter: 'github-pr-review'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

